In [50]:
%load_ext autoreload
%autoreload
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
from evaluate_model import *
from team_code import *
from run_model import *

In [45]:
import os
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib

font = {'size'   : 16}

matplotlib.rc('font', **font)

In [29]:
data_folder = "./training_subset/"

In [6]:
patient_ids = find_data_folders(data_folder)

In [7]:
patient_metadata, recording_metadata, recording_data = load_challenge_data(data_folder, patient_ids[0])

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)

In [15]:
patient_ids = np.asarray(patient_ids)
for i, (train_index, test_index) in enumerate(kf.split(np.unique(patient_ids))):
    train_id, val_id = patient_ids[train_index], patient_ids[test_index]

In [25]:
np.where(np.isin(patient_ids,train_id))[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [13]:
next(kf.split(patient_ids))

(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([0, 1, 2, 3]))

In [ ]:
for i, (train_index, test_index) in enumerate(kf.split(patient_ids)):
    train


In [8]:
patient_metadata

'Patient: ICARE_0284\nAge: 53\nSex: Male\nROSC: nan\nOHCA: True\nVFib: True\nTTM: 33\nOutcome: Good\nCPC: 1\n'

In [9]:
get_patient_id(patient_metadata)

'ICARE_0284'

In [19]:
for rec in recording_data:
    if rec[1] != None:
        for lead in rec[0]:
            print(lead)

[-0.15625  0.625    1.375   ... -4.90625 -3.625   -2.3125 ]
[-0.375   -0.0625   0.96875 ... -8.65625 -5.375   -0.09375]
[ 0.375    0.84375  0.53125 ...  3.      -1.25    -0.28125]
[ 2.375    3.21875  4.15625 ...  0.125    0.3125  -3.5625 ]
[-0.03125  0.5      0.5     ... -1.75    -2.09375 -1.53125]
[ 0.25    -0.21875  1.34375 ...  0.96875  6.4375  -1.     ]
[ 0.625    1.625    2.03125 ... -2.875   -4.34375  0.21875]
[ 1.375    2.34375  2.09375 ... -2.5625  -3.09375 -0.34375]
[-0.71875 -0.375   -0.21875 ...  2.5      1.5     -0.65625]
[ 0.9375  -0.125   -0.1875  ... 10.875    6.84375 -7.96875]
[ -2.8125   -0.5625    1.78125 ... -15.5625  -10.84375   4.40625]
[ 4.8125  5.75    5.75   ... -8.25   -7.4375 -2.125 ]
[-1.40625 -1.5     -1.375   ... -0.1875  -5.96875 -1.375  ]
[-0.5     -0.1875   0.90625 ... -0.21875  0.53125  0.34375]
[ 1.59375  2.40625  3.78125 ... -1.96875  4.21875 -1.125  ]
[ 2.5      3.5625   2.6875  ... -3.8125  -1.9375  -0.46875]
[-0.34375 -0.09375  0.59375 ... -2.125  

In [52]:
challenge_score, auroc_outcomes, auprc_outcomes, accuracy_outcomes, f_measure_outcomes, mse_cpcs, mae_cpcs = cross_validate_model("./training_subset/",2,1)

Finding the Challenge data...
Extracting features and labels from the Challenge data...
Split the data into 2 cross-validation folds
Fold 0:
Inception model built.
Inception model built.
Training the Challenge models on the Challenge data...
Epoch 1/15
 1/15 [=>............................] - ETA: 2:01 - loss: 0.6529 - ROC: 0.0000e+00 - PRC: 0.0000e+00