In [66]:
import pytest
import numpy as np
import os
import numpy.ma as ma

In [52]:
from helper_code import load_challenge_data, get_shockable_rhythm

In [53]:
from team_code import get_patient_features

In [35]:
def test_get_patient_features():
    features = get_patient_features(load_challenge_data("./training_subset/","ICARE_0284"))
    correct = np.array([53,0,1,0,np.nan,1,None,33])
    assert np.array_equal(correct[[0,1,2,3,5,7]],features[[0,1,2,3,5,7]],equal_nan=False)

In [ ]:

np.where(np.isnan(a), ma.array(a, mask=np.isnan(a)).mean(axis=0), a) 

In [127]:
a = np.zeros((len(os.listdir("./training_subset/"))-1,8))
for i,j in enumerate(os.listdir("./training_subset/")):
    if j != "RECORDS":
        a[i,:] = get_patient_features(load_challenge_data("./training_subset/",j))
#b = np.where(np.isnan(a), ma.array(a, mask=np.isnan(a)).mean(axis=0), a)

In [131]:
a[:,6].all()

True

In [119]:
def clean_tabular_data(data):
    data[:,0] = nan_to_mean(data[:,0])
    data[:,4] = nan_to_mean(data[:,4])
    data[:,5] = nan_to_median(data[:,5])
    data[:,6] = nan_to_median(data[:,6])
    data[:,7] = nan_to_median(data[:,7])
    return data

In [113]:
def nan_to_mean(arr):
    if arr.all():
        return np.zeros((len(arr)))
    else:
        mean = np.nanmean(arr)
        return np.nan_to_num(arr,nan=mean)

In [112]:
def nan_to_median(arr):
    if arr.all():
        return np.zeros((len(arr)))
    else:
        median = np.nanmedian(arr)
        return np.nan_to_num(arr,nan=median)

In [106]:
np.nanmedian(a[:,5])

1.0

In [103]:
nan_to_mean(a[:,4])

array([26.77777778,  7.        , 26.77777778, 26.77777778, 24.        ,
       20.        , 26.77777778, 26.77777778,  3.        , 37.        ,
       26.77777778, 20.        , 26.77777778, 40.        , 60.        ,
       26.77777778, 26.77777778, 26.77777778, 30.        , 26.77777778])

In [97]:
mean = np.nanmean(a[:,4])

In [98]:
np.nan_to_num(a[:,4],nan=mean)

array([26.77777778,  7.        , 26.77777778, 26.77777778, 24.        ,
       20.        , 26.77777778, 26.77777778,  3.        , 37.        ,
       26.77777778, 20.        , 26.77777778, 40.        , 60.        ,
       26.77777778, 26.77777778, 26.77777778, 30.        , 26.77777778])

In [79]:
print(b)

[[53.          0.          1.          0.         26.77777778  1.
   0.         33.        ]
 [85.          1.          0.          0.          7.          0.
   0.         33.33333333]
 [48.          0.          1.          0.         26.77777778  1.
   0.         36.        ]
 [45.          0.          1.          0.         26.77777778  1.
   0.         33.        ]
 [51.          0.          1.          0.         24.          1.
   0.         33.        ]
 [73.          0.          1.          0.         20.          1.
   0.         33.        ]
 [39.          1.          0.          0.         26.77777778  1.
   0.         33.        ]
 [51.          0.          1.          0.         26.77777778  0.68421053
   0.         33.33333333]
 [56.          0.          1.          0.          3.          0.
   0.         33.        ]
 [41.          0.          1.          0.         37.          1.
   0.         33.        ]
 [62.          0.          1.          0.         26.77777778 

In [50]:
features = get_patient_features(load_challenge_data("./training_subset/","ICARE_0284"))
correct = np.array([53,0,1,0,np.nan,1,None,33])

assert np.array_equal(correct[[0,1,2,3,5,7]],features[[0,1,2,3,5,7]],equal_nan=False)

In [48]:
correct[[0,1,2,3,5,7]]

array([53, 0, 1, 0, 1, 33], dtype=object)

In [36]:
test_get_patient_features()

AssertionError: 

In [14]:
get_shockable_rhythm(load_challenge_data("./training_subset/","ICARE_0284"))

In [8]:
get_patient_features(load_challenge_data("./training_subset/","ICARE_0284"))

array([53, 0, 1, 0, nan, 1, None, 33], dtype=object)

In [ ]:
"/training_subset/ICARE_0284/ICARE_0284.txt"